// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/course-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseRequest) Reset() {
	*x = CourseRequest{}
	mi := &file_proto_course_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseRequest) ProtoMessage() {}

func (x *CourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseRequest.ProtoReflect.Descriptor instead.
func (*CourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{0}
}

func (x *CourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseResponse) Reset() {
	*x = CourseResponse{}
	mi := &file_proto_course_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseResponse) ProtoMessage() {}

func (x *CourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseResponse.ProtoReflect.Descriptor instead.
func (*CourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{1}
}

func (x *CourseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CourseID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseID) Reset() {
	*x = CourseID{}
	mi := &file_proto_course_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseID) ProtoMessage() {}

func (x *CourseID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseID.ProtoReflect.Descriptor instead.
func (*CourseID) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{2}
}

func (x *CourseID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_course_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrollRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_course_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_course_service_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_course_service_proto protoreflect.FileDescriptor

const file_proto_course_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/course-service.proto\x12\x06course\"G\n" +
	"\rCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"X\n" +
	"\x0eCourseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x1a\n" +
	"\bCourseID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\rEnrollRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcourseId\x18\x02 \x01(\tR\bcourseId\"*\n" +
	"\x0eEnrollResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc4\x01\n" +
	"\rCourseService\x12=\n" +
	"\fCreateCourse\x12\x15.course.CourseRequest\x1a\x16.course.CourseResponse\x125\n" +
	"\tGetCourse\x12\x10.course.CourseID\x1a\x16.course.CourseResponse\x12=\n" +
	"\fEnrollCourse\x12\x15.course.EnrollRequest\x1a\x16.course.EnrollResponseB;Z9github.com/sudhin-az/E-LEARNING-GRPC/course-service/protob\x06proto3"

var (
	file_proto_course_service_proto_rawDescOnce sync.Once
	file_proto_course_service_proto_rawDescData []byte
)

func file_proto_course_service_proto_rawDescGZIP() []byte {
	file_proto_course_service_proto_rawDescOnce.Do(func() {
		file_proto_course_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_course_service_proto_rawDesc), len(file_proto_course_service_proto_rawDesc)))
	})
	return file_proto_course_service_proto_rawDescData
}

var file_proto_course_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_course_service_proto_goTypes = []any{
	(*CourseRequest)(nil),  // 0: course.CourseRequest
	(*CourseResponse)(nil), // 1: course.CourseResponse
	(*CourseID)(nil),       // 2: course.CourseID
	(*EnrollRequest)(nil),  // 3: course.EnrollRequest
	(*EnrollResponse)(nil), // 4: course.EnrollResponse
}
var file_proto_course_service_proto_depIdxs = []int32{
	0, // 0: course.CourseService.CreateCourse:input_type -> course.CourseRequest
	2, // 1: course.CourseService.GetCourse:input_type -> course.CourseID
	3, // 2: course.CourseService.EnrollCourse:input_type -> course.EnrollRequest
	1, // 3: course.CourseService.CreateCourse:output_type -> course.CourseResponse
	1, // 4: course.CourseService.GetCourse:output_type -> course.CourseResponse
	4, // 5: course.CourseService.EnrollCourse:output_type -> course.EnrollResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_course_service_proto_init() }
func file_proto_course_service_proto_init() {
	if File_proto_course_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_course_service_proto_rawDesc), len(file_proto_course_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_course_service_proto_goTypes,
		DependencyIndexes: file_proto_course_service_proto_depIdxs,
		MessageInfos:      file_proto_course_service_proto_msgTypes,
	}.Build()
	File_proto_course_service_proto = out.File
	file_proto_course_service_proto_goTypes = nil
	file_proto_course_service_proto_depIdxs = nil
}
